source "https://rubygems.org"
ruby '2.5.1'
gem 'rspec'
gem 'rubocop', '~> 0.57.2'
gem 'pry'
gem 'dotenv'
gem 'twitter'
gem 'nokogiri'
gem 'rubygems-update'
gem 'rubygems-find'
gem 'open-uri'
gem 'rubygems'
